import y2021.*

@main def main(day: String): Unit =
  println(s"Welcome to day $day")
  day match {
    case "01" => Day01.run()
    case "02" => throw UnsupportedOperationException()
    case "03" => throw UnsupportedOperationException()
    case "04" => throw UnsupportedOperationException()
    case "05" => throw UnsupportedOperationException()
    case "06" => Day06.run()
    case "07" => Day07.run()
    case "08" => Day08.run()
    case "09" => Day09.run()
    case "10" => Day10.run()
    case "11" => Day11.run()
    case "12" => Day12.run()
    case "13" => Day13.run()
    case "14" => Day14.run()
    case "15" => Day15.run()
    case "16" => Day16.run()
    case "17" => Day17.run()
    case "18" => Day18.run()
    case "19" => Day19.run()
    case "20" => Day20.run()
    case "21" => Day21.run()
    case "22" => Day22.run()
    case "23" => Day23.run()
    case "24" => throw UnsupportedOperationException()
    case "25" => throw UnsupportedOperationException()
    case _    => throw RuntimeException(s"Invalid day $day")
  }
