@main def main(day: String): Unit =
  println(s"Welcome to day $day")
  day match {
    case "01" => Day01.run()
    case "02" => throw UnsupportedOperationException()
    case "03" => throw UnsupportedOperationException()
    case "04" => throw UnsupportedOperationException()
    case "05" => Day05.run()
    case "06" => Day06.run()
    case "07" => Day07.run()
    case "08" => Day08.run()
    case "09" => Day09.run()
    case "10" => Day10.run()
    case "11" => Day11.run()
    case "12" => Day12.run()
    case "13" => Day13.run()
    case "14" => Day14.run()
    case "15" => Day15.run()
    case "16" => Day16.run()
    case "17" => Day17.run()
    case "18" => throw UnsupportedOperationException()
    case "19" => throw UnsupportedOperationException()
    case "20" => throw UnsupportedOperationException()
    case "21" => throw UnsupportedOperationException()
    case "22" => throw UnsupportedOperationException()
    case "23" => throw UnsupportedOperationException()
    case "24" => throw UnsupportedOperationException()
    case "25" => throw UnsupportedOperationException()
    case _ => throw RuntimeException(s"Invalid day $day")
  }

